# Assignment Day 3 | 11th November 2020
                              Done By : Varinderjot Singh

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as n

In [5]:
ans=n.arange(start=2,stop=50,step=3)
print(ans)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [24]:
lst1 = []   
lst2 = []   
  
lst1 = [int(item) for item in input("Enter the list items : ").split()] 
  
lst2 = [int(item) for item in input("Enter the list items : ").split()] 
  
arr1 = n.array(lst1)
arr2 = n.array(lst2)
arr = n.concatenate((arr1, arr2))
print(arr)
print("After Sorting: ",n.sort(arr))

Enter the list items : 2 4 56 23 5
Enter the list items : 90 24 7 12 28
[ 2  4 56 23  5 90 24  7 12 28]
After Sorting:  [ 2  4  5  7 12 23 24 28 56 90]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [8]:
arr = n.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
arr = n.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = n.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [21]:
a = n.array([[1, 2], 
              [3, 4]]) 
  
b = n.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical :\n ",n.vstack((a, b)))
print("-------")
# horizontal stacking 
print("Horizontal : \n",n.hstack((a,b)))

Vertical :
  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------
Horizontal : 
 [[1 2 5 6]
 [3 4 7 8]]


# Questions 6:
How to get unique items and counts of unique items?

In [11]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
new_set = set(input_list) 
print(new_set)
print("No of unique items in the list are:", len(new_set))

{1, 2, 4, 5, 8}
No of unique items in the list are: 5
